INSERT INTO estado (idestado, nome) VALUES (1, 'AC');
INSERT INTO estado (idestado, nome) VALUES (2, 'AL');
INSERT INTO estado (idestado, nome) VALUES (3, 'AP');
INSERT INTO estado (idestado, nome) VALUES (4, 'AM');
INSERT INTO estado (idestado, nome) VALUES (5, 'BA');
INSERT INTO estado (idestado, nome) VALUES (6, 'CE');
INSERT INTO estado (idestado, nome) VALUES (7, 'DF');
INSERT INTO estado (idestado, nome) VALUES (8, 'ES');
INSERT INTO estado (idestado, nome) VALUES (9, 'GO');
INSERT INTO estado (idestado, nome) VALUES (10, 'MA');
INSERT INTO estado (idestado, nome) VALUES (11, 'MT');
INSERT INTO estado (idestado, nome) VALUES (12, 'MS');
INSERT INTO estado (idestado, nome) VALUES (13, 'MG');
INSERT INTO estado (idestado, nome) VALUES (14, 'PA');
INSERT INTO estado (idestado, nome) VALUES (15, 'PB');
INSERT INTO estado (idestado, nome) VALUES (16, 'PR');
INSERT INTO estado (idestado, nome) VALUES (17, 'PE');
INSERT INTO estado (idestado, nome) VALUES (18, 'PI');
INSERT INTO estado (idestado, nome) VALUES (19, 'RJ');
INSERT INTO estado (idestado, nome) VALUES (20, 'RN');
INSERT INTO estado (idestado, nome) VALUES (21, 'RS');
INSERT INTO estado (idestado, nome) VALUES (22, 'RO');
INSERT INTO estado (idestado, nome) VALUES (23, 'RR');
INSERT INTO estado (idestado, nome) VALUES (24, 'SC');
INSERT INTO estado (idestado, nome) VALUES (25, 'SP');
INSERT INTO estado (idestado, nome) VALUES (26, 'SE');
INSERT INTO estado (idestado, nome) VALUES (27, 'TO');
INSERT INTO laboratorio (idlaboratorio, nome) VALUES (1, 'VIxPharmaceos');
INSERT INTO laboratorio (idlaboratorio, nome) VALUES (2, 'GrandFundation Labs');
INSERT INTO laboratorio (idlaboratorio, nome) VALUES (3, 'Sandox');
INSERT INTO laboratorio (idlaboratorio, nome) VALUES (4, 'Janssen-Cilag');
INSERT INTO laboratorio (idlaboratorio, nome) VALUES (5, 'Farmoquímica');
INSERT INTO laboratorio (idlaboratorio, nome) VALUES (6, 'Tylenol');
INSERT INTO laboratorio (idlaboratorio, nome) VALUES (7, 'Teuto');
INSERT INTO laboratorio (idlaboratorio, nome) VALUES (8, 'Testuvil');
INSERT INTO laboratorio (idlaboratorio, nome) VALUES (9, 'Estemitourito');
INSERT INTO laboratorio (idlaboratorio, nome) VALUES (10, 'LabsLbas');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (1, 'ABACAVIR', './arquivos/bulas/ABACAVIR.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (2, 'ACETATO DE MEDROXIPROGESTERONA ', './arquivos/bulas/ACETATODEMEDROXIPROGESTERONA.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (3, 'ACETAZOLAMIDA', './arquivos/bulas/ACETAZOLAMIDA.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (4, 'ACICLOVIR E ACICLOVIR SÓDICO', './arquivos/bulas/ACICLOVIREACICLOVIRSÓDICO.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (5, 'ÁCIDO ACETILSALICÍLICO', './arquivos/bulas/ÁCIDOACETILSALICÍLICO.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (6, 'ÁCIDO FÓLICO', './arquivos/bulas/ÁCIDOFÓLICO.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (7, 'ACIDO VALPROICO (OU VALPROATO DE SODIO)', './arquivos/bulas/ACIDOVALPROICO(OUVALPROATODESODIO).html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (8, 'ALBENDAZOL', './arquivos/bulas/ALBENDAZOL.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (9, 'ALENDRONATO DE SÓDIO', './arquivos/bulas/ALENDRONATODESÓDIO.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (10, 'ALOPURINOL', './arquivos/bulas/ALOPURINOL.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (11, 'AMIODARONA, CLORIDRATO DE', './arquivos/bulas/AMIODARONA,CLORIDRATODE.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (12, 'AMITRIPTILINA, CLORIDRATO DE', './arquivos/bulas/AMITRIPTILINA,CLORIDRATODE.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (13, 'AMOXICILINA', './arquivos/bulas/AMOXICILINA.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (14, 'AMOXICILINA COM CLAVULANATO DE POTÁSSIO', './arquivos/bulas/AMOXICILINACOMCLAVULANATODEPOTÁSSIO.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (15, 'ANLODIPINO', './arquivos/bulas/ANLODIPINO.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (16, 'ATENOLOL', './arquivos/bulas/ATENOLOL.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (17, 'AZITROMICINA', './arquivos/bulas/AZITROMICINA.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (18, 'Abacavir', './arquivos/bulas/Abacavir.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (19, 'Abatacepte', './arquivos/bulas/Abatacepte.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (20, 'Abciximabe', './arquivos/bulas/Abciximabe.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (21, 'Acarbose', './arquivos/bulas/Acarbose.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (22, 'Acebrofilina', './arquivos/bulas/Acebrofilina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (23, 'Aceclofenaco', './arquivos/bulas/Aceclofenaco.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (24, 'Aceponato de Metilprednisolona', './arquivos/bulas/AceponatodeMetilprednisolona.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (25, 'Acetado de Atosibano', './arquivos/bulas/AcetadodeAtosibano.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (26, 'Acetato De Alfatocoferol', './arquivos/bulas/AcetatoDeAlfatocoferol.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (27, 'Bacillus Cereus', './arquivos/bulas/BacillusCereus.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (28, 'Bacillus Clausii', './arquivos/bulas/BacillusClausii.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (29, 'Bacitracina', './arquivos/bulas/Bacitracina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (30, 'Baclofeno', './arquivos/bulas/Baclofeno.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (31, 'Bacopa Monnieri', './arquivos/bulas/BacopaMonnieri.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (32, 'Baryta Carbonica + Atropa Belladona', './arquivos/bulas/BarytaCarbonica+AtropaBelladona.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (33, 'Basiliximabe', './arquivos/bulas/Basiliximabe.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (34, 'Belatacepte', './arquivos/bulas/Belatacepte.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (35, 'Belimumabe', './arquivos/bulas/Belimumabe.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (36, 'Belladonna', './arquivos/bulas/Belladonna.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (37, 'Bemiparina Sódica', './arquivos/bulas/BemiparinaSódica.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (38, 'Bendamustina', './arquivos/bulas/Bendamustina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (39, 'Benfotiamina', './arquivos/bulas/Benfotiamina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (40, 'Benzbromarona', './arquivos/bulas/Benzbromarona.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (41, 'Benzilpenicilina Benzatina', './arquivos/bulas/BenzilpenicilinaBenzatina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (42, 'Benzilpenicilina Potássica', './arquivos/bulas/BenzilpenicilinaPotássica.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (43, 'Capecitabina', './arquivos/bulas/Capecitabina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (44, 'Capsaicina', './arquivos/bulas/Capsaicina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (45, 'Captopril', './arquivos/bulas/Captopril.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (46, 'Captopril', './arquivos/bulas/Captopril.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (47, 'Carbamazepina', './arquivos/bulas/Carbamazepina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (48, 'Carbidopa', './arquivos/bulas/Carbidopa.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (49, 'Carbocisteína', './arquivos/bulas/Carbocisteína.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (50, 'Carbonato De Cálcio', './arquivos/bulas/CarbonatoDeCálcio.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (51, 'Carbonato de Lodenafila', './arquivos/bulas/CarbonatodeLodenafila.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (52, 'Carbonato de Lítio', './arquivos/bulas/CarbonatodeLítio.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (53, 'Carbonato de Sevelâmero', './arquivos/bulas/CarbonatodeSevelâmero.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (54, 'Carboplatina', './arquivos/bulas/Carboplatina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (55, 'Carboximaltose Férrica', './arquivos/bulas/CarboximaltoseFérrica.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (56, 'Dacarbazina', './arquivos/bulas/Dacarbazina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (57, 'Daclatasvir', './arquivos/bulas/Daclatasvir.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (58, 'Dactinomicina', './arquivos/bulas/Dactinomicina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (59, 'Dalteparina Sódica', './arquivos/bulas/DalteparinaSódica.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (60, 'Danazol', './arquivos/bulas/Danazol.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (61, 'Dantroleno Sódico', './arquivos/bulas/DantrolenoSódico.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (62, 'Dapagliflozina', './arquivos/bulas/Dapagliflozina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (63, 'Dapoxetina', './arquivos/bulas/Dapoxetina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (64, 'Dapsona', './arquivos/bulas/Dapsona.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (65, 'Daptomicina', './arquivos/bulas/Daptomicina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (66, 'Daratumumabe', './arquivos/bulas/Daratumumabe.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (67, 'Darunavir', './arquivos/bulas/Darunavir.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (68, 'Dasatinibe', './arquivos/bulas/Dasatinibe.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (69, 'Daunorrubicina Liposomal', './arquivos/bulas/DaunorrubicinaLiposomal.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (70, 'Decanoato de Haloperidol', './arquivos/bulas/DecanoatodeHaloperidol.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (71, 'Decanoato de Nandrolona', './arquivos/bulas/DecanoatodeNandrolona.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (72, 'Decitabina', './arquivos/bulas/Decitabina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (73, 'Deferasirox', './arquivos/bulas/Deferasirox.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (74, 'Deferiprona', './arquivos/bulas/Deferiprona.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (75, 'Deflazacorte', './arquivos/bulas/Deflazacorte.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (76, 'Deltafolitropina', './arquivos/bulas/Deltafolitropina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (77, 'Deltametrina', './arquivos/bulas/Deltametrina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (78, 'Denosumabe', './arquivos/bulas/Denosumabe.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (79, 'Ebastina', './arquivos/bulas/Ebastina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (80, 'Eculizumabe', './arquivos/bulas/Eculizumabe.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (81, 'Edoxabana', './arquivos/bulas/Edoxabana.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (82, 'Efavirenz', './arquivos/bulas/Efavirenz.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (83, 'Elbasvir', './arquivos/bulas/Elbasvir.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (84, 'Eletrólitos', './arquivos/bulas/Eletrólitos.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (85, 'Elotuzumabe', './arquivos/bulas/Elotuzumabe.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (86, 'Eltrombopague Olamina', './arquivos/bulas/EltrombopagueOlamina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (87, 'Embonato de Pirvínio', './arquivos/bulas/EmbonatodePirvínio.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (88, 'Empagliflozina', './arquivos/bulas/Empagliflozina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (89, 'Enflurano', './arquivos/bulas/Enflurano.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (90, 'Enfuvirtida', './arquivos/bulas/Enfuvirtida.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (91, 'Enoxaparina Sódica', './arquivos/bulas/EnoxaparinaSódica.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (92, 'Entacapona', './arquivos/bulas/Entacapona.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (93, 'Entecavir', './arquivos/bulas/Entecavir.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (94, 'Entricitabina', './arquivos/bulas/Entricitabina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (95, 'Enxofre', './arquivos/bulas/Enxofre.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (96, 'Enzalutamida', './arquivos/bulas/Enzalutamida.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (97, 'Equinacea Purpurea', './arquivos/bulas/EquinaceaPurpurea.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (98, 'Ergocalciferol', './arquivos/bulas/Ergocalciferol.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (99, 'Eritromicina', './arquivos/bulas/Eritromicina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (100, 'Eritropoetina Humana', './arquivos/bulas/EritropoetinaHumana.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (101, 'Ertapeném Sódico', './arquivos/bulas/ErtapenémSódico.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (102, 'Escina', './arquivos/bulas/Escina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (103, 'Esilato de Nintedanibe', './arquivos/bulas/EsilatodeNintedanibe.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (104, 'Esomeprazol Magnésico', './arquivos/bulas/EsomeprazolMagnésico.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (105, 'Esomeprazol Sódico', './arquivos/bulas/EsomeprazolSódico.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (106, 'Famotidina', './arquivos/bulas/Famotidina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (107, 'Fampridina', './arquivos/bulas/Fampridina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (108, 'Fanciclovir', './arquivos/bulas/Fanciclovir.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (109, 'Felodipino', './arquivos/bulas/Felodipino.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (110, 'Femprocumona', './arquivos/bulas/Femprocumona.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (111, 'Fendizoato de Cloperastina', './arquivos/bulas/FendizoatodeCloperastina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (112, 'Fenilbutazona Cálcica', './arquivos/bulas/FenilbutazonaCálcica.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (113, 'Fenitoína', './arquivos/bulas/Fenitoína.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (114, 'Fenobarbital', './arquivos/bulas/Fenobarbital.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (115, 'Fenofibrato', './arquivos/bulas/Fenofibrato.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (116, 'Fenol', './arquivos/bulas/Fenol.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (117, 'Fenoprofeno Cálcico', './arquivos/bulas/FenoprofenoCálcico.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (118, 'Fenoximetilpenicilina Potássica', './arquivos/bulas/FenoximetilpenicilinaPotássica.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (119, 'Fentanila', './arquivos/bulas/Fentanila.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (120, 'Gabapentina', './arquivos/bulas/Gabapentina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (121, 'Gadobutrol', './arquivos/bulas/Gadobutrol.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (122, 'Gadodiamida', './arquivos/bulas/Gadodiamida.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (123, 'Gadopentato de Dimeglumina', './arquivos/bulas/GadopentatodeDimeglumina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (124, 'Gadoteridol', './arquivos/bulas/Gadoteridol.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (125, 'Gadoversetamida', './arquivos/bulas/Gadoversetamida.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (126, 'Gadoxetato Dissódico', './arquivos/bulas/GadoxetatoDissódico.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (127, 'Galsulfase', './arquivos/bulas/Galsulfase.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (128, 'Ganciclovir', './arquivos/bulas/Ganciclovir.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (129, 'Ganirelix', './arquivos/bulas/Ganirelix.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (130, 'Gatifloxacino', './arquivos/bulas/Gatifloxacino.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (131, 'Halotano', './arquivos/bulas/Halotano.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (132, 'Hamamelis Virginiana', './arquivos/bulas/HamamelisVirginiana.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (133, 'Harpagophytum Procumbens', './arquivos/bulas/HarpagophytumProcumbens.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (134, 'Hedera Helix', './arquivos/bulas/HederaHelix.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (135, 'Hemifumarato de Alisquireno', './arquivos/bulas/HemifumaratodeAlisquireno.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (136, 'Hemifumarato de Quetiapina', './arquivos/bulas/HemifumaratodeQuetiapina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (137, 'Hemitartarato de Eliglustate', './arquivos/bulas/HemitartaratodeEliglustate.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (138, 'Hemitartarato de Metaraminol', './arquivos/bulas/HemitartaratodeMetaraminol.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (139, 'Hemitartarato de Norepinefrina', './arquivos/bulas/HemitartaratodeNorepinefrina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (140, 'Hemitartarato de Rivastigmina', './arquivos/bulas/HemitartaratodeRivastigmina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (141, 'Hemitartarato de Zolpidem', './arquivos/bulas/HemitartaratodeZolpidem.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (142, 'Heparina', './arquivos/bulas/Heparina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (143, 'Heparina Sódica', './arquivos/bulas/HeparinaSódica.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (144, 'Heparina Sódica + Nicotinato de Benzila', './arquivos/bulas/HeparinaSódica+NicotinatodeBenzila.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (145, 'Hexacetonida de Triancinolona', './arquivos/bulas/HexacetonidadeTriancinolona.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (146, 'Hexafluoreto de Enxofre', './arquivos/bulas/HexafluoretodeEnxofre.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (147, 'Hexamidina + Tetracaína', './arquivos/bulas/Hexamidina+Tetracaína.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (148, 'Hialuronato de Sódio', './arquivos/bulas/HialuronatodeSódio.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (149, 'Hialuronidase', './arquivos/bulas/Hialuronidase.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (150, 'Hialuronidase + Betametasona', './arquivos/bulas/Hialuronidase+Betametasona.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (151, 'Hidralazina', './arquivos/bulas/Hidralazina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (152, 'Hidrato de Calcipotriol + Dipropionato de Betametasona', './arquivos/bulas/HidratodeCalcipotriol+DipropionatodeBetametasona.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (153, 'Hidroclorotiazida', './arquivos/bulas/Hidroclorotiazida.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (154, 'Ibandronato de Sódio', './arquivos/bulas/IbandronatodeSódio.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (155, 'Ibrutinibe', './arquivos/bulas/Ibrutinibe.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (156, 'Ibuprofeno', './arquivos/bulas/Ibuprofeno.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (157, 'Ibuprofeno + Arginina', './arquivos/bulas/Ibuprofeno+Arginina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (158, 'Icodextrina', './arquivos/bulas/Icodextrina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (159, 'Idarucizumabe', './arquivos/bulas/Idarucizumabe.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (160, 'Idoxuridina', './arquivos/bulas/Idoxuridina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (161, 'Idursulfase', './arquivos/bulas/Idursulfase.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (162, 'Ifosfamida', './arquivos/bulas/Ifosfamida.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (163, 'Iloprosta', './arquivos/bulas/Iloprosta.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (164, 'Imiglucerase', './arquivos/bulas/Imiglucerase.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (165, 'Imipeném + Cilastatina Sódica', './arquivos/bulas/Imipeném+CilastatinaSódica.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (166, 'Imiquimode', './arquivos/bulas/Imiquimode.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (167, 'Imunoglobulina', './arquivos/bulas/Imunoglobulina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (168, 'Imunoglobulina G', './arquivos/bulas/ImunoglobulinaG.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (169, 'Imunoglobulina Humana', './arquivos/bulas/ImunoglobulinaHumana.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (170, 'Imunoglobulina Humana Anti-Hepatite B', './arquivos/bulas/ImunoglobulinaHumanaAnti-HepatiteB.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (171, 'Imunoglobulina antitimócito', './arquivos/bulas/Imunoglobulinaantitimócito.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (172, 'Indapamida', './arquivos/bulas/Indapamida.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (173, 'Indinavir', './arquivos/bulas/Indinavir.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (174, 'Secuquinumabe', './arquivos/bulas/Secuquinumabe.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (175, 'Senna Alexandrina Mill', './arquivos/bulas/SennaAlexandrinaMill.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (176, 'Senna Alexandrina Mill + Associações', './arquivos/bulas/SennaAlexandrinaMill+Associações.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (177, 'Senna alexandrina Miller + Cassia fistula L.', './arquivos/bulas/SennaalexandrinaMiller+CassiafistulaL..html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (178, 'Serenoa Repens', './arquivos/bulas/SerenoaRepens.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (179, 'Serenoa Serrulata + Vitaminas + Zinco', './arquivos/bulas/SerenoaSerrulata+Vitaminas+Zinco.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (180, 'Sevoflurano', './arquivos/bulas/Sevoflurano.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (181, 'Silimarina + Racemetionina', './arquivos/bulas/Silimarina+Racemetionina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (182, 'Silodosina', './arquivos/bulas/Silodosina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (183, 'Siltuximabe', './arquivos/bulas/Siltuximabe.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (184, 'Silybum Marianum L. Gaerth', './arquivos/bulas/SilybumMarianumL.Gaerth.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (185, 'Simeprevir Sódico', './arquivos/bulas/SimeprevirSódico.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (186, 'Simeticona', './arquivos/bulas/Simeticona.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (187, 'Simeticona + Metilbrometo de Homatropina', './arquivos/bulas/Simeticona+MetilbrometodeHomatropina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (188, 'Sinvastatina', './arquivos/bulas/Sinvastatina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (189, 'Sirolimo', './arquivos/bulas/Sirolimo.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (190, 'Xilometazolina', './arquivos/bulas/Xilometazolina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (191, 'Zafirlucaste', './arquivos/bulas/Zafirlucaste.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (192, 'Zanamivir', './arquivos/bulas/Zanamivir.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (193, 'Zidovudina', './arquivos/bulas/Zidovudina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (194, 'Zinco', './arquivos/bulas/Zinco.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (195, 'Zolmitriptano', './arquivos/bulas/Zolmitriptano.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (196, 'Zopiclona', './arquivos/bulas/Zopiclona.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (197, 'Zuclopentixol', './arquivos/bulas/Zuclopentixol.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (198, 'Tacrolimo', './arquivos/bulas/Tacrolimo.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (199, 'Tacrolimo Monoidratado', './arquivos/bulas/TacrolimoMonoidratado.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (200, 'Tadalafila', './arquivos/bulas/Tadalafila.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (201, 'Tafamidis Meglumina', './arquivos/bulas/TafamidisMeglumina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (202, 'Tafluprosta', './arquivos/bulas/Tafluprosta.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (203, 'Talidomida', './arquivos/bulas/Talidomida.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (204, 'Tanacetum Parthenium', './arquivos/bulas/TanacetumParthenium.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (205, 'Tartarato de Metoprolol', './arquivos/bulas/TartaratodeMetoprolol.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (206, 'Tartarato de Vareniclina', './arquivos/bulas/TartaratodeVareniclina.html');
INSERT INTO medicamento (idmedicamento, nome, bula) VALUES (207, 'Tartarato de Vinorelbina', './arquivos/bulas/TartaratodeVinorelbina.html');
